_BASE_: Base-Mask-Refiner.yaml
MODEL:
  BACKBONE:
    NAME: "build_resnet_deeplab_rgbd_fusion_backbone"
    FUSION_STRATEGY: "concat"
    NUM_FUSION_LAYERS: 2
SOLVER:
  OPTIMIZER: "ADAM"
  BASE_LR: 0.000125
  IMS_PER_BATCH: 8