_BASE_: Base-Mask-Refiner.yaml
MODEL:
  BACKBONE:
    NAME: "build_resnet_deeplab_rgbd_fusion_backbone"
    FUSION_STRATEGY: "concat"
    NUM_FUSION_LAYERS: 2
  INS_EMBED_HEAD:
    HIERARCHICAL_FUSION_ON: True
    HIERARCHY: [["eee_boundary"], ["eee_mask"], ["foreground"], ["center"], ["offset"]]
    NUM_FUSION_LAYERS: 3
    FUSION_TARGET: ["feat", "pred"]
SOLVER:
  OPTIMIZER: "ADAM"
  BASE_LR: 0.000125
  IMS_PER_BATCH: 2