MODEL:
  WEIGHTS: "detectron2://DeepLab/R-52.pkl"
  META_ARCHITECTURE: "MaskRefiner"
  BACKBONE:
    NAME: "build_resnet_deeplab_rgbd_fusion_backbone"
    FUSION_STRATEGY: "add"
    NUM_FUSION_LAYERS: 3
    FREEZE_AT: 0
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res5"]
    RES5_DILATION: 2
  PIXEL_MEAN: [103.530, 116.280, 123.675, 127.5, 127.5, 127.5] 
  PIXEL_STD: [1, 1, 1, 1, 1, 1]
  INS_EMBED_HEAD:
    NAME: "MaskRefinerInsEmbedHead"
    IN_FEATURES: ["res2", "res3", "res5"]
    PROJECT_FEATURES: ["res2", "res3"]
    PROJECT_CHANNELS: [32, 64]
    ASPP_CHANNELS: 256
    ASPP_DILATIONS: [6, 12, 18]
    ASPP_DROPOUT: 0.1
    HEAD_CHANNELS: 32
    CONVS_DIM: 128
    COMMON_STRIDE: 4
    NORM: "GN"
    FOREGROUND_LOSS_WEIGHT: 1.0
    FOREGROUND_LOSS_TYPE: "hard_pixel_mining"
    FOREGROUND_LOSS_TOP_K: 1.0
    CENTER_LOSS_WEIGHT: 200.0
    OFFSET_LOSS_WEIGHT: 0.01
    EEE_MASK_ON: True
    EEE_MASK_LOSS_WEIGHT: 1.0
    EEE_BOUNDARY_ON: True
    EEE_BOUNDARY_LOSS_WEIGHT: 1.0
    EEE_POST_PROCESS_ON: True
  PANOPTIC_DEEPLAB:
    STUFF_AREA: 2048
    CENTER_THRESHOLD: 0.1
    NMS_KERNEL: 7
    TOP_K_INSTANCE: 200
    USE_DEPTHWISE_SEPARABLE_CONV: True
DATASETS:
  TRAIN: ("uoais_sim_train_panoptic", "tod_v2_train_panoptic")
  TEST: ("uoais_sim_val_panoptic",)
SOLVER:
  OPTIMIZER: "ADAM"
  BASE_LR: 0.000125
  WEIGHT_DECAY: 0.0
  WEIGHT_DECAY_NORM: 0.0
  WEIGHT_DECAY_BIAS: 0.0
  MAX_ITER: 90000
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  IMS_PER_BATCH: 4
  CHECKPOINT_PERIOD: 10000
INPUT:
  MIN_SIZE_TRAIN: (480,)
  MAX_SIZE_TRAIN: 640
  MIN_SIZE_TEST: 480
  MAX_SIZE_TEST: 640
  OFFSET_INPUT_ON: True
  CROP:
    ENABLED: False
  DEPTH_ON: True
  DEPTH_RANGE: [2500, 15000] 
  PERLIN_DISTORTION_ON: True
  COLOR_AUG_SSD: True
TEST:
  EVAL_PERIOD: 30000
DATALOADER:
  NUM_WORKERS: 1
VERSION: 2
SEED: 7
