_BASE_: ../Base-Mask-Refiner.yaml
MODEL:
  RESNETS:
    DEPTH: 101
  BACKBONE:
    NAME: "build_resnet_deeplab_rgbd_fusion_backbone"
    FUSION_STRATEGY: "concat"
    NUM_FUSION_LAYERS: 2
  INS_EMBED_HEAD:
    HIERARCHICAL_FUSION_ON: True
    EEE_MASK_ON: False
    HIERARCHY: [["eee_boundary"], ["foreground", "center", "offset"]]
    NUM_FUSION_LAYERS: 3
    FUSION_TARGET: ["feat", "pred"]
    ERROR_TYPE: "e3"
SOLVER:
  OPTIMIZER: "ADAM"
  BASE_LR: 0.000125
  IMS_PER_BATCH: 8
  WEIGHT_DECAY: 0.0
  WEIGHT_DECAY_NORM: 0.0
  WEIGHT_DECAY_BIAS: 0.0
  MAX_ITER: 900000
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  IMS_PER_BATCH: 8
  CHECKPOINT_PERIOD: 30000
SEED: 777