_BASE_: ../Base-Mask-Refiner.yaml
MODEL:
  BACKBONE:
    NAME: "build_resnet_deeplab_rgbd_fusion_backbone"
    FUSION_STRATEGY: "concat"
    NUM_FUSION_LAYERS: 2
  INS_EMBED_HEAD:
    HIERARCHICAL_FUSION_ON: True
    HIERARCHY: [["foreground"], ["center"], ["offset"], ["eee_mask"], ["eee_boundary"]]
    NUM_FUSION_LAYERS: 3
    FUSION_TARGET: ["feat", "pred"]
    ERROR_TYPE: "e3"
SOLVER:
  OPTIMIZER: "ADAM"
  BASE_LR: 0.000125
  IMS_PER_BATCH: 8
SEED: 7777